title: “Minuet in G Major” (BWV Anh. 114) and “Minuet in G Minor” (BWV Anh. 115) by Christian Petzold
baseurl: /lilypond-piano-bwvanh114-115
url: https://jeandeaual.github.io
repository: jeandeaual/lilypond-piano-bwvanh114-115
lang: en-US
show_downloads: false
# Build settings
theme: jekyll-theme-minimal
plugins: []
defaults:
  - scope:
      path: "a4"
    values:
      a4: true
  - scope:
      path: "letter"
    values:
      letter: true
  - scope:
      path: "svg"
    values:
      svg: true
  - scope:
      path: "midi"
    values:
      midi: true
